window.addEventListener('load',()=>{let progress=0;const counter=document.querySelector('.counter');const bar=document.querySelector('.fill');const loader=document.querySelector('.preloader');const interval=setInterval(()=>{progress+=Math.floor(Math.random()*10)+5;if(progress>100)progress=100;counter.textContent=progress+'%';bar.style.width=progress+'%';if(progress===100){clearInterval(interval);setTimeout(()=>{loader.classList.add('fade-out');document.body.classList.remove('loading');initHeroAnimations()},500)}},50)});const magneticElements=document.querySelectorAll('.magnetic');magneticElements.forEach(elem=>{elem.addEventListener('mousemove',(e)=>{const rect=elem.getBoundingClientRect();const strength=elem.dataset.strength||20;const x=(e.clientX-rect.left-rect.width/2)*(strength/100);const y=(e.clientY-rect.top-rect.height/2)*(strength/100);elem.style.transform=`translate(${x}px, ${y}px)`});elem.addEventListener('mouseleave',()=>{elem.style.transform=`translate(0px, 0px)`})});const tiltBox=document.querySelector('.tilt-box');const portraitImg=document.querySelector('.portrait-img');if(tiltBox&&portraitImg){tiltBox.addEventListener('mousemove',(e)=>{const rect=tiltBox.getBoundingClientRect();const x=e.clientX-rect.left;const y=e.clientY-rect.top;const centerX=rect.width/2;const centerY=rect.height/2;const tiltX=(y-centerY)/20;const tiltY=(centerX-x)/20;tiltBox.style.transform=`perspective(1000px) rotateX(${tiltX}deg) rotateY(${tiltY}deg)`;portraitImg.style.transform=`scale(1.1) translate(${tiltY * 0.5}px, ${-tiltX * 0.5}px)`});tiltBox.addEventListener('mouseleave',()=>{tiltBox.style.transform=`perspective(1000px) rotateX(0deg) rotateY(0deg)`;portraitImg.style.transform=`scale(1.05) translate(0px, 0px)`})}
window.addEventListener('scroll',()=>{const scrollY=window.scrollY;const coverImgs=document.querySelectorAll('.cover-img');coverImgs.forEach(img=>{const parent=img.parentElement;const parentTop=parent.getBoundingClientRect().top;const speed=0.15;if(parentTop<window.innerHeight&&parentTop>-parent.offsetHeight){const yPos=(parentTop-window.innerHeight/2)*speed;img.style.transform=`translateY(${yPos}px)`}});const shrinkTexts=document.querySelectorAll('.scroll-shrink');shrinkTexts.forEach((text,i)=>{const rect=text.getBoundingClientRect();if(rect.top<window.innerHeight&&rect.bottom>0){const move=(window.innerHeight-rect.top)*0.1*(i%2===0?1:-1);text.style.transform=`translate(calc(-50% + ${move}px), -50%)`}})});const fadeUpElements=document.querySelectorAll('.animate-fade-up');const observerOptions={root:null,rootMargin:'0px',threshold:0.15};const styleSheet=document.createElement("style");styleSheet.innerText=`
    .animate-fade-up {
        opacity: 0;
        transform: translateY(40px);
        transition: opacity 1s cubic-bezier(0.19, 1, 0.22, 1), transform 1s cubic-bezier(0.19, 1, 0.22, 1);
    }
    .animate-fade-up.visible {
        opacity: 1;
        transform: translateY(0);
    }
`;document.head.appendChild(styleSheet);const fadeUpObserver=new IntersectionObserver((entries,observer)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},observerOptions);fadeUpElements.forEach(el=>fadeUpObserver.observe(el));document.querySelectorAll('.marquee-row').forEach(row=>{const track=row.querySelector('.marquee-track');const content=track.innerHTML;track.innerHTML=content+content+content;const direction=row.getAttribute('data-direction');let position=0;const speed=direction==='left'?-1:1;let isHovered=!1;row.addEventListener('mouseenter',()=>isHovered=!0);row.addEventListener('mouseleave',()=>isHovered=!1);setTimeout(()=>{const thirdWidth=track.scrollWidth/3;if(direction==='right')position=-thirdWidth;const step=()=>{if(!isHovered){position+=speed;if(direction==='left'&&Math.abs(position)>=thirdWidth){position=0}else if(direction==='right'&&position>=0){position=-thirdWidth}
track.style.transform=`translateX(${position}px)`}
requestAnimationFrame(step)};requestAnimationFrame(step)},100)});function initHeroAnimations(){const reveals=document.querySelectorAll('.reveal-text');const visual=document.querySelector('.reveal-visual');const revealStyle=document.createElement("style");revealStyle.innerText=`
        .reveal-text {
            opacity: 0;
            transform: translateY(30px) rotate(2deg);
            transition: opacity 1.2s cubic-bezier(0.19, 1, 0.22, 1), transform 1.2s cubic-bezier(0.19, 1, 0.22, 1);
        }
        .reveal-text.delay-1 { transition-delay: 0.1s; }
        .reveal-text.delay-2 { transition-delay: 0.2s; }
        .reveal-text.active {
            opacity: 1;
            transform: translateY(0) rotate(0);
        }
        .reveal-visual {
            opacity: 0;
            transform: scale(0.9) translateY(40px);
            transition: opacity 1.5s cubic-bezier(0.19, 1, 0.22, 1) 0.3s, transform 1.5s cubic-bezier(0.19, 1, 0.22, 1) 0.3s;
        }
        .reveal-visual.active {
            opacity: 1;
            transform: scale(1) translateY(0);
        }
    `;document.head.appendChild(revealStyle);setTimeout(()=>{reveals.forEach(r=>r.classList.add('active'));if(visual)visual.classList.add('active');},100)}
const translations={en:{navAbout:"About",navStack:"Stack",navWork:"Work",navContact:"Contact",heroSubtitle:"Junior High School (SMP) Web Developer in Indonesia",heroBtn:"Explore The Project",aboutLead:"I am a <span class='highlight-text'>Junior High School (SMP) student</span>, I am already dedicated to crafting digital experiences that aren't just functional, but emotionally engaging. I blend young, bold, and creative ideas with solid programming logic.",workHeader:"Selected Works",p1Desc:"Experience 3D Sculpting with your hands. A web-based Augmented Reality engine using MediaPipe and Three.js.",pLink:"Live Preview &nearr;",p2Desc:"Website for motorbike and car rental with a modern and attractive design.",p3Desc:"Official Class Website featuring structure & archives for easy access.",footerCta:"HAVE AN IDEA?",footerTalk:"LET'S TALK.",footerRights:"&copy; 2026 I Kadek Rafa Waradana. All Rights Reserved."},id:{navAbout:"Tentang",navStack:"Teknologi",navWork:"Karya",navContact:"Kontak",heroSubtitle:"Developer Web & Siswa SMP di Indonesia",heroBtn:"Eksplorasi Proyek",aboutLead:"Sebagai seorang <span class='highlight-text'>pelajar SMP</span>, saya telah berdedikasi menciptakan pengalaman digital yang tidak hanya fungsional, tapi juga menggugah secara emosional. Memadukan ide muda, berani, & kreatif dengan logika pemrograman yang solid.",workHeader:"Karya Pilihan",p1Desc:"Rasakan pengalaman memahat 3D dengan tangan kosong. Mesin Augmented Reality berbasis web menggunakan MediaPipe & Three.js.",pLink:"Cek Webnya &nearr;",p2Desc:"Website penyewaan motor dan mobil dengan desain yang modern dan atraktif.",p3Desc:"Website Kelas Resmi dengan fitur struktur kelas & arsip yang mudah diakses.",footerCta:"PUNYA IDE KEREN?",footerTalk:"MARI NGOBROL.",footerRights:"&copy; 2026 I Kadek Rafa Waradana. Hak Cipta Dilindungi."}};let currentLang='en';const btnEn=document.getElementById('lang-en');const btnId=document.getElementById('lang-id');function setLanguage(lang){if(!translations[lang])return;currentLang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.getAttribute('data-i18n');if(translations[lang][key]){el.innerHTML=translations[lang][key]}});if(lang==='en'){btnEn.classList.add('active');btnId.classList.remove('active')}else{btnId.classList.add('active');btnEn.classList.remove('active')}}
if(btnEn&&btnId){btnEn.addEventListener('click',()=>setLanguage('en'));btnId.addEventListener('click',()=>setLanguage('id'))}
