const cursorDot=document.getElementById('cursor-dot');const cursorOutline=document.getElementById('cursor-outline');const magneticElements=document.querySelectorAll('.magnetic');const web3=document.getElementById("web3")
window.addEventListener('mousemove',(e)=>{const posX=e.clientX;const posY=e.clientY;cursorDot.style.left=`${posX}px`;cursorDot.style.top=`${posY}px`;cursorOutline.animate({left:`${posX}px`,top:`${posY}px`},{duration:500,fill:"forwards"})});document.querySelectorAll('a, button, .nav-item, .bento-card').forEach(el=>{el.addEventListener('mouseenter',()=>document.body.classList.add('hovering'));el.addEventListener('mouseleave',()=>document.body.classList.remove('hovering'))});magneticElements.forEach(btn=>{btn.addEventListener('mousemove',(e)=>{const rect=btn.getBoundingClientRect();const x=e.clientX-rect.left-rect.width/2;const y=e.clientY-rect.top-rect.height/2;btn.style.transform=`translate(${x * 0.2}px, ${y * 0.2}px)`});btn.addEventListener('mouseleave',()=>{btn.style.transform='translate(0px, 0px)'})});const canvas=document.getElementById('hero-canvas');const ctx=canvas.getContext('2d');canvas.width=window.innerWidth;canvas.height=window.innerHeight;let particlesArray;window.addEventListener('resize',()=>{canvas.width=window.innerWidth;canvas.height=window.innerHeight;initParticles()});const mouse={x:null,y:null,radius:150}
window.addEventListener('mousemove',(e)=>{mouse.x=e.x;mouse.y=e.y});class Particle{constructor(x,y,directionX,directionY,size,color){this.x=x;this.y=y;this.directionX=directionX;this.directionY=directionY;this.size=size;this.color=color}
draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.size,0,Math.PI*2,!1);ctx.fillStyle='#00f2ff';ctx.fill()}
update(){if(this.x>canvas.width||this.x<0)this.directionX=-this.directionX;if(this.y>canvas.height||this.y<0)this.directionY=-this.directionY;let dx=mouse.x-this.x;let dy=mouse.y-this.y;let distance=Math.sqrt(dx*dx+dy*dy);if(distance<mouse.radius+this.size){if(mouse.x<this.x&&this.x<canvas.width-10)this.x+=3;if(mouse.x>this.x&&this.x>10)this.x-=3;if(mouse.y<this.y&&this.y<canvas.height-10)this.y+=3;if(mouse.y>this.y&&this.y>10)this.y-=3}
this.x+=this.directionX;this.y+=this.directionY;this.draw()}}
function initParticles(){particlesArray=[];let numberOfParticles=(canvas.width*canvas.height)/15000;for(let i=0;i<numberOfParticles;i++){let size=(Math.random()*2)+1;let x=(Math.random()*((innerWidth-size*2)-(size*2))+size*2);let y=(Math.random()*((innerHeight-size*2)-(size*2))+size*2);let directionX=(Math.random()*0.4)-0.2;let directionY=(Math.random()*0.4)-0.2;let color='#00f2ff';particlesArray.push(new Particle(x,y,directionX,directionY,size,color))}}
function animateParticles(){requestAnimationFrame(animateParticles);ctx.clearRect(0,0,innerWidth,innerHeight);for(let i=0;i<particlesArray.length;i++){particlesArray[i].update()}
connectParticles()}
function connectParticles(){let opacityValue=1;for(let a=0;a<particlesArray.length;a++){for(let b=a;b<particlesArray.length;b++){let distance=((particlesArray[a].x-particlesArray[b].x)*(particlesArray[a].x-particlesArray[b].x))+((particlesArray[a].y-particlesArray[b].y)*(particlesArray[a].y-particlesArray[b].y));if(distance<(canvas.width/7)*(canvas.height/7)){opacityValue=1-(distance/20000);ctx.strokeStyle='rgba(0, 242, 255,'+opacityValue*0.15+')';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(particlesArray[a].x,particlesArray[a].y);ctx.lineTo(particlesArray[b].x,particlesArray[b].y);ctx.stroke()}}}}
initParticles();animateParticles();const observerOptions={threshold:0.2};const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){if(entry.target.classList.contains('skill-item')){const bar=entry.target.querySelector('.progress-fill');bar.style.transform="scaleX(1)"}
if(entry.target.classList.contains('stat-item')){const numEl=entry.target.querySelector('.stat-num');const targetVal=parseInt(numEl.getAttribute('data-val'));let currentVal=0;const timer=setInterval(()=>{if(currentVal>=targetVal){clearInterval(timer)}else{currentVal++;numEl.innerText=currentVal+"+"}},50)}
observer.unobserve(entry.target)}})},observerOptions);document.querySelectorAll('.skill-item, .stat-item').forEach(el=>{observer.observe(el)});const sections=document.querySelectorAll("section");const navLi=document.querySelectorAll(".dock-nav .nav-item");window.addEventListener("scroll",()=>{let current="";sections.forEach((section)=>{const sectionTop=section.offsetTop;const sectionHeight=section.clientHeight;if(scrollY>=(sectionTop-sectionHeight/3)){current=section.getAttribute("id")}});navLi.forEach((li)=>{li.classList.remove("active");if(li.getAttribute("href").includes(current)){li.classList.add("active")}})});console.log("%c SYSTEM STATUS: ONLINE ","color: #00f2ff; background: #000; font-size: 20px; padding: 5px;")
